# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.101.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: tfupdate
      args:
        - --args=terraform
    - id: tfupdate
      args:
        - --args=provider bpg/proxmox
    - id: tfupdate
      args:
        - --args=provider hashicorp/null
    - id: tfupdate
      args:
        - --args=provider hashicorp/random
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=USAGE.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - id: terraform_tflint
