name: Terraform code quality
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/lint.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/lint.yaml"
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      run: terraform fmt
      continue-on-error: true
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: terraform-linters/setup-tflint@v6
      name: Setup TFLint
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Run TFLint
      run: tflint -f compact
